[package]
name = "logos-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
console_error_panic_hook = "0.1"
rkyv = { version = "0.7", features = ["validation"] }

# Internal Dependencies
logos-protocol = { path = "../../core/logos-protocol", features = ["std"] }
logos-parser = { path = "../../compilers/logos-parser" }
logos-ecs = { path = "../../core/logos-ecs" }
logos-solver = { path = "../../compilers/logos-solver" }
